// Generated by scripts/sync-decor-catalog.ts from
// https://github.com/Kadantte/discord-fake-avatar-decorations (a community
// mirror of Discord's official avatar decoration store, slug-keyed).
// DO NOT EDIT BY HAND.
import type { AvatarDecoration } from './avatar-decorations'
export const GENERATED_DECORATIONS: AvatarDecoration[] = [
  {
    "slug": "new_year_2025",
    "name": "2025 Balloons"
  },
  {
    "slug": "28_years_later",
    "name": "28 Years Later"
  },
  {
    "slug": "a_duck",
    "name": "a duck"
  },
  {
    "slug": "a_hint_of_clove",
    "name": "A Hint of Clove"
  },
  {
    "slug": "a_real_fungi",
    "name": "A Real Fungi"
  },
  {
    "slug": "aespa_fanlight",
    "name": "aespa Fanlight"
  },
  {
    "slug": "afternoon_breeze",
    "name": "Afternoon Breeze"
  },
  {
    "slug": "aim_for_love",
    "name": "Aim for Love"
  },
  {
    "slug": "air",
    "name": "Air"
  },
  {
    "slug": "airona_fireworks",
    "name": "Airona Fireworks"
  },
  {
    "slug": "akuma",
    "name": "Akuma"
  },
  {
    "slug": "all_might",
    "name": "All Might"
  },
  {
    "slug": "angel",
    "name": "Angel"
  },
  {
    "slug": "angela_avatar",
    "name": "Angela Avatar"
  },
  {
    "slug": "angry",
    "name": "Angry"
  },
  {
    "slug": "angry_pink",
    "name": "Angry (Pink)"
  },
  {
    "slug": "angry_yellow",
    "name": "Angry (Yellow)"
  },
  {
    "slug": "frog_angry",
    "name": "Angry Frog"
  },
  {
    "slug": "arcane_sigil",
    "name": "Arcane Sigil"
  },
  {
    "slug": "armamenter",
    "name": "Armamenter"
  },
  {
    "slug": "astral_aura",
    "name": "Astral Aura"
  },
  {
    "slug": "astronaut_helmet",
    "name": "Astronaut Helmet"
  },
  {
    "slug": "atsus_mask",
    "name": "Atsu's Mask"
  },
  {
    "slug": "aurora",
    "name": "Aurora"
  },
  {
    "slug": "autumn_crown",
    "name": "Autumn Crown"
  },
  {
    "slug": "autumn_foliage",
    "name": "Autumn Foliage"
  },
  {
    "slug": "autumns_arbor",
    "name": "Autumn's Arbor"
  },
  {
    "slug": "autumns_arbor_aurora",
    "name": "Autumn's Arbor (Aurora)"
  },
  {
    "slug": "dice_azure",
    "name": "Azure Dice"
  },
  {
    "slug": "baby_displacer_beast",
    "name": "Baby Displacer Beast"
  },
  {
    "slug": "baker_bear",
    "name": "Baker Bear"
  },
  {
    "slug": "balance",
    "name": "Balance"
  },
  {
    "slug": "ballerina",
    "name": "Ballerina"
  },
  {
    "slug": "bandit_mask",
    "name": "Bandit Mask"
  },
  {
    "slug": "batarang",
    "name": "Batarang"
  },
  {
    "slug": "beach_hat",
    "name": "Beach Hat"
  },
  {
    "slug": "beamchop",
    "name": "Beamchop"
  },
  {
    "slug": "berry_bunny",
    "name": "Berry Bunny"
  },
  {
    "slug": "bf_soldier_helmet",
    "name": "BF Soldier Helmet"
  },
  {
    "slug": "big_dill_chain",
    "name": "Big Dill Chain"
  },
  {
    "slug": "bing_bong",
    "name": "Bing Bong"
  },
  {
    "slug": "black_hole",
    "name": "Black Hole"
  },
  {
    "slug": "black_mana",
    "name": "Black Mana"
  },
  {
    "slug": "black_phone_2",
    "name": "Black Phone 2"
  },
  {
    "slug": "blade_storm",
    "name": "Blade Storm"
  },
  {
    "slug": "bloodthirsty",
    "name": "Bloodthirsty"
  },
  {
    "slug": "bloodthirsty_gold",
    "name": "Bloodthirsty (Gold)"
  },
  {
    "slug": "bloodthirsty_green",
    "name": "Bloodthirsty (Green)"
  },
  {
    "slug": "bloomling",
    "name": "Bloomling"
  },
  {
    "slug": "blossomburst",
    "name": "Blossomburst"
  },
  {
    "slug": "box_blue_yellow",
    "name": "Blue Box"
  },
  {
    "slug": "blue_futuristic_ui",
    "name": "Blue Futuristic UI"
  },
  {
    "slug": "gelatinous_cube_blue",
    "name": "Blue Gelatinous Cube"
  },
  {
    "slug": "blue_gyroscope",
    "name": "Blue Gyroscope"
  },
  {
    "slug": "blue_hyper_helmet",
    "name": "Blue Hyper Helmet"
  },
  {
    "slug": "blue_mana",
    "name": "Blue Mana"
  },
  {
    "slug": "blue_shine_helmet",
    "name": "Blue Shine Helmet"
  },
  {
    "slug": "blue_smoke",
    "name": "Blue Smoke"
  },
  {
    "slug": "teacup_blue",
    "name": "Blue Teacup"
  },
  {
    "slug": "blueberry_jam",
    "name": "Blueberry Jam"
  },
  {
    "slug": "bonsai",
    "name": "Bonsai"
  },
  {
    "slug": "bowler_hat",
    "name": "Bowler Hat"
  },
  {
    "slug": "brass_beats",
    "name": "Brass Beats"
  },
  {
    "slug": "bread_doggy",
    "name": "Bread Doggy"
  },
  {
    "slug": "bubble",
    "name": "Bubble"
  },
  {
    "slug": "bubble_tea",
    "name": "Bubble Tea"
  },
  {
    "slug": "buffering",
    "name": "Buffering..."
  },
  {
    "slug": "bunny",
    "name": "Bunny"
  },
  {
    "slug": "bunny_zzzs",
    "name": "Bunny Zzzs"
  },
  {
    "slug": "burnt_toast",
    "name": "Burnt Toast"
  },
  {
    "slug": "bush_camper",
    "name": "Bush Camper"
  },
  {
    "slug": "butterflies",
    "name": "Butterflies"
  },
  {
    "slug": "cab_monster",
    "name": "Cab Monster"
  },
  {
    "slug": "call_of_duty_mobile",
    "name": "Call of Duty: Mobile"
  },
  {
    "slug": "cameraman_glitch",
    "name": "Cameraman Glitch"
  },
  {
    "slug": "cammy",
    "name": "Cammy"
  },
  {
    "slug": "candlelight",
    "name": "Candlelight"
  },
  {
    "slug": "cannon_fire",
    "name": "Cannon Fire"
  },
  {
    "slug": "cat_ear_headset",
    "name": "Cat Ear Headset"
  },
  {
    "slug": "cat_ears",
    "name": "Cat Ears"
  },
  {
    "slug": "cat_ears_blue",
    "name": "Cat Ears (Blue)"
  },
  {
    "slug": "cat_ears_green",
    "name": "Cat Ears (Green)"
  },
  {
    "slug": "cat_ears_purple",
    "name": "Cat Ears (Purple)"
  },
  {
    "slug": "cat_ears_yellow",
    "name": "Cat Ears (Yellow)"
  },
  {
    "slug": "cat_onesie",
    "name": "Cat Onesie"
  },
  {
    "slug": "cat_onesie_black",
    "name": "Cat Onesie (Black)"
  },
  {
    "slug": "cat_onesie_pink",
    "name": "Cat Onesie (Pink)"
  },
  {
    "slug": "cattiva",
    "name": "Cattiva"
  },
  {
    "slug": "champions_tactibear",
    "name": "Champions Tactibear"
  },
  {
    "slug": "fox_hat_chestnut",
    "name": "Chestnut Fox Hat"
  },
  {
    "slug": "chewbert",
    "name": "Chewbert"
  },
  {
    "slug": "chicken_nugget",
    "name": "Chicken Nugget"
  },
  {
    "slug": "chillet",
    "name": "Chillet"
  },
  {
    "slug": "chomp_chomp",
    "name": "Chomp Chomp"
  },
  {
    "slug": "chromawave",
    "name": "Chromawave"
  },
  {
    "slug": "chuck",
    "name": "Chuck"
  },
  {
    "slug": "chun_li",
    "name": "Chun-Li"
  },
  {
    "slug": "city_walls",
    "name": "City Walls"
  },
  {
    "slug": "clicker",
    "name": "Clicker"
  },
  {
    "slug": "clyde_invaders",
    "name": "Clyde Invaders"
  },
  {
    "slug": "constellations",
    "name": "Constellations"
  },
  {
    "slug": "copium",
    "name": "Copium"
  },
  {
    "slug": "cosy_deer",
    "name": "Cosy Deer"
  },
  {
    "slug": "cottage_home",
    "name": "Cottage Home"
  },
  {
    "slug": "cow_glider",
    "name": "Cow Glider"
  },
  {
    "slug": "cozy_cat",
    "name": "Cozy Cat"
  },
  {
    "slug": "cozy_headphones",
    "name": "Cozy Headphones"
  },
  {
    "slug": "cozy_post_it",
    "name": "Cozy Post-It"
  },
  {
    "slug": "cozy_post_it_festive",
    "name": "Cozy Post-It (Festive)"
  },
  {
    "slug": "candlelight_crimson",
    "name": "Crimson Candlelight"
  },
  {
    "slug": "hood_crimson",
    "name": "Crimson Hood"
  },
  {
    "slug": "crossbones",
    "name": "Crossbones"
  },
  {
    "slug": "crystal_ball_blue",
    "name": "Crystal Ball (Blue)"
  },
  {
    "slug": "crystal_ball_purple",
    "name": "Crystal Ball (Purple)"
  },
  {
    "slug": "crystal_elk",
    "name": "Crystal Elk"
  },
  {
    "slug": "curious_bb_8",
    "name": "Curious BB-8"
  },
  {
    "slug": "cyber_katana",
    "name": "Cyber Katana"
  },
  {
    "slug": "cybernetic",
    "name": "Cybernetic"
  },
  {
    "slug": "cypher_neural_theft",
    "name": "Cypher Neural Theft"
  },
  {
    "slug": "dancing_fairies",
    "name": "Dancing Fairies"
  },
  {
    "slug": "dandelion_duo",
    "name": "Dandelion Duo"
  },
  {
    "slug": "daredevil",
    "name": "Daredevil"
  },
  {
    "slug": "candlelight_dark",
    "name": "Dark Candlelight"
  },
  {
    "slug": "hood_dark",
    "name": "Dark Hood"
  },
  {
    "slug": "dart_monkey",
    "name": "Dart Monkey"
  },
  {
    "slug": "deaths_edge",
    "name": "Death's Edge"
  },
  {
    "slug": "defensive_shield",
    "name": "Defensive Shield"
  },
  {
    "slug": "depresso",
    "name": "Depresso"
  },
  {
    "slug": "frog_derpy",
    "name": "Derpy Frog"
  },
  {
    "slug": "descendant",
    "name": "Descendant"
  },
  {
    "slug": "devil",
    "name": "Devil"
  },
  {
    "slug": "dewdrop",
    "name": "Dewdrop"
  },
  {
    "slug": "digital_sunrise",
    "name": "Digital Sunrise"
  },
  {
    "slug": "dismay",
    "name": "Dismay"
  },
  {
    "slug": "dismay_green",
    "name": "Dismay (Green)"
  },
  {
    "slug": "dismay_pink",
    "name": "Dismay (Pink)"
  },
  {
    "slug": "dismay_purple",
    "name": "Dismay (Purple)"
  },
  {
    "slug": "dismay_yellow",
    "name": "Dismay (Yellow)"
  },
  {
    "slug": "disxcore_headset",
    "name": "DISXCORE Headset"
  },
  {
    "slug": "dog_1",
    "name": "Dogs #1"
  },
  {
    "slug": "dog_2",
    "name": "Dogs #2"
  },
  {
    "slug": "dog_3",
    "name": "Dogs #3"
  },
  {
    "slug": "donut",
    "name": "Donut"
  },
  {
    "slug": "donut_bear",
    "name": "Donut Bear"
  },
  {
    "slug": "donut_cat",
    "name": "Donut Cat"
  },
  {
    "slug": "donut_cow",
    "name": "Donut Cow"
  },
  {
    "slug": "doodlezard",
    "name": "Doodlezard"
  },
  {
    "slug": "doodling",
    "name": "Doodling"
  },
  {
    "slug": "dragon_balls",
    "name": "Dragon Balls"
  },
  {
    "slug": "dragons_smile",
    "name": "Dragon's Smile"
  },
  {
    "slug": "dream_dive_stars",
    "name": "Dream Dive Stars"
  },
  {
    "slug": "dusk_and_dawn",
    "name": "Dusk and Dawn"
  },
  {
    "slug": "e_d_hacker",
    "name": "E.D Hacker"
  },
  {
    "slug": "earth",
    "name": "Earth"
  },
  {
    "slug": "echo_4",
    "name": "Echo 4"
  },
  {
    "slug": "egg",
    "name": "Egg"
  },
  {
    "slug": "eldritch_ring",
    "name": "Eldritch Ring"
  },
  {
    "slug": "elpis",
    "name": "Elpis"
  },
  {
    "slug": "emma_frost",
    "name": "Emma Frost"
  },
  {
    "slug": "endeavor",
    "name": "Endeavor"
  },
  {
    "slug": "espn",
    "name": "ESPN"
  },
  {
    "slug": "exoborne",
    "name": "Exoborne"
  },
  {
    "slug": "eye_of_prophesy",
    "name": "Eye of Prophesy"
  },
  {
    "slug": "face_of_corruption",
    "name": "Face of Corruption"
  },
  {
    "slug": "faces_of_the_moon",
    "name": "Faces of the Moon"
  },
  {
    "slug": "fairy_sprites",
    "name": "Fairy Sprites"
  },
  {
    "slug": "fairy_sprites_blue",
    "name": "Fairy Sprites (Blue)"
  },
  {
    "slug": "fairy_sprites_pink",
    "name": "Fairy Sprites (Pink)"
  },
  {
    "slug": "fall_leaves",
    "name": "Fall Leaves"
  },
  {
    "slug": "fan_flourish",
    "name": "Fan Flourish"
  },
  {
    "slug": "fc_26_icon",
    "name": "FC 26 Icon"
  },
  {
    "slug": "feelin_awe",
    "name": "Feelin' Awe"
  },
  {
    "slug": "feelin_nervous",
    "name": "Feelin' Nervous"
  },
  {
    "slug": "feelin_panic",
    "name": "Feelin' Panic"
  },
  {
    "slug": "feelin_scrumptious",
    "name": "Feelin' Scrumptious"
  },
  {
    "slug": "feeling_cute",
    "name": "Feeling Cute"
  },
  {
    "slug": "confetti_festive",
    "name": "Festive Confetti"
  },
  {
    "slug": "finger_gun",
    "name": "Finger Gun"
  },
  {
    "slug": "fire",
    "name": "Fire"
  },
  {
    "slug": "confetti_fire",
    "name": "Fire Confetti"
  },
  {
    "slug": "firecrackers",
    "name": "Firecrackers"
  },
  {
    "slug": "fireflies",
    "name": "Fireflies"
  },
  {
    "slug": "fishbones",
    "name": "FISHBONES!"
  },
  {
    "slug": "flame_chompers",
    "name": "Flame Chompers"
  },
  {
    "slug": "flaming_sword",
    "name": "Flaming Sword"
  },
  {
    "slug": "floral_harmony",
    "name": "Floral Harmony"
  },
  {
    "slug": "floral_harmony_sunburst",
    "name": "Floral Harmony (Sunburst)"
  },
  {
    "slug": "flower_clouds",
    "name": "Flower Clouds"
  },
  {
    "slug": "flux_alchemy",
    "name": "Flux Alchemy"
  },
  {
    "slug": "forest",
    "name": "Forest"
  },
  {
    "slug": "forest_frolic",
    "name": "Forest Frolic"
  },
  {
    "slug": "fortnite_boogie_bomb",
    "name": "Fortnite Boogie Bomb"
  },
  {
    "slug": "fortnite_galactic_battle",
    "name": "Fortnite Galactic Battle"
  },
  {
    "slug": "victory_crown",
    "name": "Fortnite Victory Crown"
  },
  {
    "slug": "fox_hat",
    "name": "Fox Hat"
  },
  {
    "slug": "frag_out",
    "name": "FRAG OUT"
  },
  {
    "slug": "freezer_bunny_lovebug",
    "name": "Freezer Bunny Lovebug"
  },
  {
    "slug": "fresh_pine",
    "name": "Fresh Pine"
  },
  {
    "slug": "fresh_pine_cinnamon",
    "name": "Fresh Pine (Cinnamon)"
  },
  {
    "slug": "fresh_pine_ribbon",
    "name": "Fresh Pine (Ribbon)"
  },
  {
    "slug": "freshly_picked",
    "name": "Freshly Picked"
  },
  {
    "slug": "fried_egg",
    "name": "Fried Egg"
  },
  {
    "slug": "friend_of_dex",
    "name": "Friend of Dex"
  },
  {
    "slug": "frog_1",
    "name": "Frog #1"
  },
  {
    "slug": "frog_3",
    "name": "Frog #3"
  },
  {
    "slug": "frog_hat",
    "name": "Frog Hat"
  },
  {
    "slug": "fuchsia_agent",
    "name": "Fuchsia Agent"
  },
  {
    "slug": "pink_futuristic_ui",
    "name": "Futuristic UI"
  },
  {
    "slug": "g_toilet",
    "name": "G-Toilet"
  },
  {
    "slug": "gallica",
    "name": "Gallica"
  },
  {
    "slug": "gary_the_snail",
    "name": "Gary the Snail"
  },
  {
    "slug": "gawblehop",
    "name": "Gawblehop"
  },
  {
    "slug": "ggez",
    "name": "GGEZ"
  },
  {
    "slug": "ghosts",
    "name": "Ghosts"
  },
  {
    "slug": "git_gud",
    "name": "Git Gud"
  },
  {
    "slug": "icicle_gleaming",
    "name": "Gleaming Icicle"
  },
  {
    "slug": "glitch",
    "name": "Glitch"
  },
  {
    "slug": "glop",
    "name": "Glop"
  },
  {
    "slug": "glorio",
    "name": "Glorio"
  },
  {
    "slug": "glowing_runes",
    "name": "Glowing Runes"
  },
  {
    "slug": "goblin_stinkums",
    "name": "Goblin Stinkums"
  },
  {
    "slug": "gold_laurel_wreath",
    "name": "Gold Laurel Wreath"
  },
  {
    "slug": "golden_hex",
    "name": "Golden Hex"
  },
  {
    "slug": "gomah",
    "name": "Gomah"
  },
  {
    "slug": "gone_fishin",
    "name": "Gone Fishin'"
  },
  {
    "slug": "good_ol_pepper",
    "name": "Good Ol' Pepper"
  },
  {
    "slug": "got_xenoglossy",
    "name": "Got Xenoglossy"
  },
  {
    "slug": "grass_toucher",
    "name": "Grass Toucher"
  },
  {
    "slug": "graveyard_cat",
    "name": "Graveyard Cat"
  },
  {
    "slug": "blanket_green",
    "name": "Green Blanket"
  },
  {
    "slug": "box_green_red",
    "name": "Green Box"
  },
  {
    "slug": "green_fried_egg",
    "name": "Green Fried Egg"
  },
  {
    "slug": "green_futuristic_ui",
    "name": "Green Futuristic UI"
  },
  {
    "slug": "gelatinous_cube_green",
    "name": "Green Gelatinous Cube"
  },
  {
    "slug": "green_gyroscope",
    "name": "Green Gyroscope"
  },
  {
    "slug": "green_headset",
    "name": "Green Headset"
  },
  {
    "slug": "green_hyper_helmet",
    "name": "Green Hyper Helmet"
  },
  {
    "slug": "green_mana",
    "name": "Green Mana"
  },
  {
    "slug": "green_shine_helmet",
    "name": "Green Shine Helmet"
  },
  {
    "slug": "greenhouse_cat",
    "name": "Greenhouse Cat"
  },
  {
    "slug": "group_hug",
    "name": "Group Hug"
  },
  {
    "slug": "guile",
    "name": "Guile"
  },
  {
    "slug": "sakura_gyoiko",
    "name": "Gyoiko Sakura"
  },
  {
    "slug": "hackclaw",
    "name": "Hackclaw"
  },
  {
    "slug": "hailey",
    "name": "Hailey"
  },
  {
    "slug": "hammy",
    "name": "Hammy"
  },
  {
    "slug": "hammy_blue",
    "name": "Hammy (Blue)"
  },
  {
    "slug": "hammy_green",
    "name": "Hammy (Green)"
  },
  {
    "slug": "hammy_pink",
    "name": "Hammy (Pink)"
  },
  {
    "slug": "hank_hill",
    "name": "Hank Hill"
  },
  {
    "slug": "happy_harvest",
    "name": "Happy Harvest"
  },
  {
    "slug": "hawks",
    "name": "Hawks"
  },
  {
    "slug": "head_in_the_clouds",
    "name": "Head In the Clouds"
  },
  {
    "slug": "head_in_the_clouds_sunset",
    "name": "Head In the Clouds (Sunset)"
  },
  {
    "slug": "heart_to_heart",
    "name": "Heart-to-Heart"
  },
  {
    "slug": "heartbloom",
    "name": "Heartbloom"
  },
  {
    "slug": "heartbloom_blue",
    "name": "Heartbloom (Blue)"
  },
  {
    "slug": "heartbloom_green",
    "name": "Heartbloom (Green)"
  },
  {
    "slug": "heartbloom_purple",
    "name": "Heartbloom (Purple)"
  },
  {
    "slug": "heartbloom_yellow",
    "name": "Heartbloom (Yellow)"
  },
  {
    "slug": "heartstrings_blue",
    "name": "Heartstrings (Blue)"
  },
  {
    "slug": "heartstrings_red",
    "name": "Heartstrings (Red)"
  },
  {
    "slug": "helmsman",
    "name": "Helmsman"
  },
  {
    "slug": "hex_tiles",
    "name": "Hex Tiles"
  },
  {
    "slug": "santa_cat_ears",
    "name": "Holiday Cat Ears"
  },
  {
    "slug": "hologram_dragon",
    "name": "Hologram Dragon"
  },
  {
    "slug": "honeyblossom",
    "name": "Honeyblossom"
  },
  {
    "slug": "hoppy_boi",
    "name": "Hoppy Boi"
  },
  {
    "slug": "hoppy_day",
    "name": "Hoppy Day"
  },
  {
    "slug": "hot_shot",
    "name": "Hot Shot"
  },
  {
    "slug": "how_to_train_your_dragon",
    "name": "How to Train Your Dragon"
  },
  {
    "slug": "hugh_the_rainbow",
    "name": "Hugh the Rainbow"
  },
  {
    "slug": "human_torch",
    "name": "Human Torch"
  },
  {
    "slug": "i_love_repo",
    "name": "I Love R.E.P.O."
  },
  {
    "slug": "im_a_clown",
    "name": "I'm a Clown"
  },
  {
    "slug": "im_dancin",
    "name": "I’m Dancin’!"
  },
  {
    "slug": "confetti_ice",
    "name": "Ice Confetti"
  },
  {
    "slug": "ice_cream_frog",
    "name": "Ice Cream Frog"
  },
  {
    "slug": "ice_cube",
    "name": "Icecube"
  },
  {
    "slug": "imagination",
    "name": "Imagination"
  },
  {
    "slug": "implant",
    "name": "Implant"
  },
  {
    "slug": "in_love",
    "name": "In Love"
  },
  {
    "slug": "in_love_blue",
    "name": "In Love (Blue)"
  },
  {
    "slug": "in_love_green",
    "name": "In Love (Green)"
  },
  {
    "slug": "in_tears",
    "name": "In Tears"
  },
  {
    "slug": "in_tears_green",
    "name": "In Tears (Green)"
  },
  {
    "slug": "in_tears_pink",
    "name": "In Tears (Pink)"
  },
  {
    "slug": "in_tears_purple",
    "name": "In Tears (Purple)"
  },
  {
    "slug": "in_tears_yellow",
    "name": "In Tears (Yellow)"
  },
  {
    "slug": "infinite_swirl",
    "name": "Infinite Swirl"
  },
  {
    "slug": "invisible_woman",
    "name": "Invisible Woman"
  },
  {
    "slug": "inzoi_psycat",
    "name": "inZOI Psycat"
  },
  {
    "slug": "izuku_midoriya",
    "name": "Izuku Midoriya"
  },
  {
    "slug": "jack_o_lantern",
    "name": "Jack-o'-Lantern"
  },
  {
    "slug": "jeff_the_land_shark",
    "name": "Jeff the Land Shark"
  },
  {
    "slug": "jelly_bear",
    "name": "Jelly Bear"
  },
  {
    "slug": "jet_ring",
    "name": "Jet Ring"
  },
  {
    "slug": "jingasa",
    "name": "Jingasa"
  },
  {
    "slug": "joystick",
    "name": "Joystick"
  },
  {
    "slug": "juggernaut_astro",
    "name": "Juggernaut Astro"
  },
  {
    "slug": "jurassic_world_rebirth",
    "name": "Jurassic World Rebirth Trailer"
  },
  {
    "slug": "juri",
    "name": "Juri"
  },
  {
    "slug": "kabuto",
    "name": "Kabuto"
  },
  {
    "slug": "katsuki_bakugo",
    "name": "Katsuki Bakugo"
  },
  {
    "slug": "ken",
    "name": "Ken"
  },
  {
    "slug": "khazan",
    "name": "Khazan"
  },
  {
    "slug": "ki_energy",
    "name": "Ki Energy"
  },
  {
    "slug": "ki_energy_blue",
    "name": "Ki Energy (Blue)"
  },
  {
    "slug": "ki_energy_cyan",
    "name": "Ki Energy (Cyan)"
  },
  {
    "slug": "ki_energy_fuchsia",
    "name": "Ki Energy (Fuchsia)"
  },
  {
    "slug": "ki_energy_green",
    "name": "Ki Energy (Green)"
  },
  {
    "slug": "kitsune",
    "name": "Kitsune"
  },
  {
    "slug": "koi_pond",
    "name": "Koi Pond"
  },
  {
    "slug": "kom",
    "name": "KOM"
  },
  {
    "slug": "lamball",
    "name": "Lamball"
  },
  {
    "slug": "lava_blobs",
    "name": "Lava Blobs"
  },
  {
    "slug": "lava_blobs_blue",
    "name": "Lava Blobs (Blue)"
  },
  {
    "slug": "lava_blobs_pink",
    "name": "Lava Blobs (Pink)"
  },
  {
    "slug": "lava_blobs_slime",
    "name": "Lava Blobs (Slime)"
  },
  {
    "slug": "cat_1",
    "name": "Lazy Cat #1"
  },
  {
    "slug": "cat_2",
    "name": "Lazy Cat #2"
  },
  {
    "slug": "cat_3",
    "name": "Lazy Cat #3"
  },
  {
    "slug": "cat_4",
    "name": "Lazy Cat #4"
  },
  {
    "slug": "lego_fortnite",
    "name": "LEGO® Fortnite"
  },
  {
    "slug": "lightning",
    "name": "Lightning"
  },
  {
    "slug": "lights_camera_action_orange",
    "name": "Lights, Camera, Action! (Orange)"
  },
  {
    "slug": "lights_camera_action_teal",
    "name": "Lights, Camera, Action! (Teal)"
  },
  {
    "slug": "lightsabers_blue_and_red",
    "name": "Lightsabers (Blue and Red)"
  },
  {
    "slug": "lightsabers_green_and_red",
    "name": "Lightsabers (Green and Red)"
  },
  {
    "slug": "liquid_moon",
    "name": "Liquid Moon"
  },
  {
    "slug": "lofi_girl_outfit",
    "name": "Lofi Girl Outfit"
  },
  {
    "slug": "loot_lightshow",
    "name": "Loot Lightshow"
  },
  {
    "slug": "los_santos",
    "name": "Los Santos"
  },
  {
    "slug": "lotus_flower",
    "name": "Lotus Flower"
  },
  {
    "slug": "lover_girl_autumn",
    "name": "Lover Girl Autumn"
  },
  {
    "slug": "lovestruck",
    "name": "Lovestruck"
  },
  {
    "slug": "lucky_envelopes",
    "name": "Lucky Envelopes"
  },
  {
    "slug": "luminescent_lotus",
    "name": "Luminescent Lotus"
  },
  {
    "slug": "luna_moths",
    "name": "Luna Moths"
  },
  {
    "slug": "lunar_flowers",
    "name": "Lunar Flowers"
  },
  {
    "slug": "lunar_lanterns",
    "name": "Lunar Lanterns"
  },
  {
    "slug": "m_bison",
    "name": "M. Bison"
  },
  {
    "slug": "m3gan_2_0",
    "name": "M3GAN 2.0"
  },
  {
    "slug": "mad_moxxi",
    "name": "Mad Moxxi"
  },
  {
    "slug": "magic_mists",
    "name": "Magic Mists"
  },
  {
    "slug": "magic_portal_blue",
    "name": "Magic Portal (Blue)"
  },
  {
    "slug": "magic_portal_purple",
    "name": "Magic Portal (Purple)"
  },
  {
    "slug": "magical_girl",
    "name": "Magical Girl"
  },
  {
    "slug": "magical_potion",
    "name": "Magical Potion"
  },
  {
    "slug": "magical_wand_green",
    "name": "Magical Wand (Green)"
  },
  {
    "slug": "magical_wand_purple",
    "name": "Magical Wand (Purple)"
  },
  {
    "slug": "malefic_crown",
    "name": "Malefic Crown"
  },
  {
    "slug": "mallow_jump",
    "name": "Mallow Jump"
  },
  {
    "slug": "marvel_snap_venom",
    "name": "Marvel Snap Venom"
  },
  {
    "slug": "mech_flora",
    "name": "Mech Flora"
  },
  {
    "slug": "mecha_break",
    "name": "Mecha BREAK"
  },
  {
    "slug": "mermaid_serenade",
    "name": "Mermaid Serenade"
  },
  {
    "slug": "midnight_sorceress",
    "name": "Midnight Sorceress"
  },
  {
    "slug": "witch_hat_midnight",
    "name": "Midnight Witch Hat"
  },
  {
    "slug": "millennium_falcon_hyperdrive",
    "name": "Millennium Falcon Hyperdrive"
  },
  {
    "slug": "mini_goku",
    "name": "Mini Goku"
  },
  {
    "slug": "mini_piccolo",
    "name": "Mini Piccolo"
  },
  {
    "slug": "mini_supreme_kai",
    "name": "Mini Supreme Kai"
  },
  {
    "slug": "mini_vegeta",
    "name": "Mini Vegeta"
  },
  {
    "slug": "minions",
    "name": "Minions"
  },
  {
    "slug": "confetti_mint",
    "name": "Mint Confetti"
  },
  {
    "slug": "mirage",
    "name": "Mirage"
  },
  {
    "slug": "mirage_nightshade",
    "name": "Mirage (Nightshade)"
  },
  {
    "slug": "mirage_twilight",
    "name": "Mirage (Twilight)"
  },
  {
    "slug": "mirage_void",
    "name": "Mirage (Void)"
  },
  {
    "slug": "mischievous_kitties",
    "name": "Mischievous Kitties"
  },
  {
    "slug": "mischievous_kitties_blue",
    "name": "Mischievous Kitties (Blue)"
  },
  {
    "slug": "mischievous_kitties_hearts",
    "name": "Mischievous Kitties (Hearts)"
  },
  {
    "slug": "mission_impossible",
    "name": "Mission: Impossible"
  },
  {
    "slug": "mister_fantastic",
    "name": "Mister Fantastic"
  },
  {
    "slug": "mochi_bunny_blue",
    "name": "Mochi Bunny (Blue)"
  },
  {
    "slug": "mochi_bunny_pink",
    "name": "Mochi Bunny (Pink)"
  },
  {
    "slug": "mokoko",
    "name": "Mokoko"
  },
  {
    "slug": "moomoo_hood",
    "name": "Moomoo Hood"
  },
  {
    "slug": "mooncaps_blue",
    "name": "Mooncaps (Blue)"
  },
  {
    "slug": "mooncaps_pink",
    "name": "Mooncaps (Pink)"
  },
  {
    "slug": "moonlit_charms",
    "name": "Moonlit Charms"
  },
  {
    "slug": "chrysanthemums_morning",
    "name": "Morning Chrysanthemums"
  },
  {
    "slug": "morning_coffee",
    "name": "Morning Coffee"
  },
  {
    "slug": "mr_m",
    "name": "Mr. M"
  },
  {
    "slug": "musclebob",
    "name": "MuscleBob"
  },
  {
    "slug": "mushcaps",
    "name": "Mushcaps"
  },
  {
    "slug": "mushroom_1",
    "name": "Mushroom #1"
  },
  {
    "slug": "mushroom_2",
    "name": "Mushroom #2"
  },
  {
    "slug": "mushroom_3",
    "name": "Mushroom #3"
  },
  {
    "slug": "mushroom_4",
    "name": "Mushroom #4"
  },
  {
    "slug": "nba_2k26",
    "name": "NBA 2K26"
  },
  {
    "slug": "neon_cat_hoodie",
    "name": "Neon Cat Hoodie"
  },
  {
    "slug": "neon_cat_hoodie_black",
    "name": "Neon Cat Hoodie (Black)"
  },
  {
    "slug": "neon_cat_hoodie_blue",
    "name": "Neon Cat Hoodie (Blue)"
  },
  {
    "slug": "neon_cat_hoodie_pink",
    "name": "Neon Cat Hoodie (Pink)"
  },
  {
    "slug": "neon_decora_hair",
    "name": "Neon Decora Hair"
  },
  {
    "slug": "neon_nibbles",
    "name": "Neon Nibbles"
  },
  {
    "slug": "neon_spike_choker",
    "name": "Neon Spike Choker"
  },
  {
    "slug": "neon_spike_choker_black",
    "name": "Neon Spike Choker (Black)"
  },
  {
    "slug": "new_year_2024",
    "name": "New Year"
  },
  {
    "slug": "next_turn_button",
    "name": "Next Turn Button"
  },
  {
    "slug": "nibbles",
    "name": "Nibbles"
  },
  {
    "slug": "nom_kitty",
    "name": "Nom Kitty"
  },
  {
    "slug": "o_n_i",
    "name": "O.N.I"
  },
  {
    "slug": "oasis",
    "name": "Oasis"
  },
  {
    "slug": "ochaco_uraraka",
    "name": "Ochaco Uraraka"
  },
  {
    "slug": "omens_cowl",
    "name": "Omen's Cowl"
  },
  {
    "slug": "oni_mask",
    "name": "Oni Mask"
  },
  {
    "slug": "open_beta",
    "name": "Open Beta"
  },
  {
    "slug": "blanket_orange",
    "name": "Orange Blanket"
  },
  {
    "slug": "teacup_orange",
    "name": "Orange Teacup"
  },
  {
    "slug": "owlbear_cub",
    "name": "Owlbear Cub"
  },
  {
    "slug": "pal_sphere",
    "name": "Pal Sphere"
  },
  {
    "slug": "palia",
    "name": "Palia"
  },
  {
    "slug": "pancakes",
    "name": "Pancakes"
  },
  {
    "slug": "panzy",
    "name": "Panzy"
  },
  {
    "slug": "pathojen",
    "name": "Pathojen"
  },
  {
    "slug": "patrick_star",
    "name": "Patrick Star"
  },
  {
    "slug": "phoenix",
    "name": "Phoenix"
  },
  {
    "slug": "jean_grey_phoenix",
    "name": "Phoenix"
  },
  {
    "slug": "blanket_pink",
    "name": "Pink Blanket"
  },
  {
    "slug": "pink_gyroscope",
    "name": "Pink Gyroscope"
  },
  {
    "slug": "pink_headset",
    "name": "Pink Headset"
  },
  {
    "slug": "pink_hyper_helmet",
    "name": "Pink Hyper Helmet"
  },
  {
    "slug": "sakura_pink",
    "name": "Pink Sakura"
  },
  {
    "slug": "pink_shine_helmet",
    "name": "Pink Shine Helmet"
  },
  {
    "slug": "pink_smoke",
    "name": "Pink Smoke"
  },
  {
    "slug": "teacup_pink",
    "name": "Pink Teacup"
  },
  {
    "slug": "pipedream",
    "name": "Pipedream"
  },
  {
    "slug": "pirate_captain",
    "name": "Pirate Captain"
  },
  {
    "slug": "playful_lofi_cat",
    "name": "Playful Lofi Cat"
  },
  {
    "slug": "witch_hat_plum",
    "name": "Plum Witch Hat"
  },
  {
    "slug": "polar_bear_hat",
    "name": "Polar Bear Hat"
  },
  {
    "slug": "pondering_portal",
    "name": "Pondering Portal"
  },
  {
    "slug": "port_of_soul",
    "name": "Port of Soul"
  },
  {
    "slug": "powered_by_shimmer",
    "name": "Powered by Shimmer"
  },
  {
    "slug": "press_f_black",
    "name": "Press F (Black)"
  },
  {
    "slug": "press_f_white",
    "name": "Press F (White)"
  },
  {
    "slug": "pumpkin_spice",
    "name": "Pumpkin Spice"
  },
  {
    "slug": "blanket_purple",
    "name": "Purple Blanket"
  },
  {
    "slug": "questionable",
    "name": "Questionable"
  },
  {
    "slug": "r2_d2_on_tatooine",
    "name": "R2-D2 on Tatooine"
  },
  {
    "slug": "r6_siege_x_avatar",
    "name": "R6 Siege X Avatar"
  },
  {
    "slug": "radiating_energy",
    "name": "Radiating Energy"
  },
  {
    "slug": "radiating_energy_blue",
    "name": "Radiating Energy (Blue)"
  },
  {
    "slug": "radiating_energy_yellow",
    "name": "Radiating Energy (Yellow)"
  },
  {
    "slug": "rage",
    "name": "Rage"
  },
  {
    "slug": "rage_blue",
    "name": "Rage (Blue)"
  },
  {
    "slug": "rage_green",
    "name": "Rage (Green)"
  },
  {
    "slug": "rage_purple",
    "name": "Rage (Purple)"
  },
  {
    "slug": "rage_red",
    "name": "Rage (Red)"
  },
  {
    "slug": "rainy_canopy",
    "name": "Rainy Canopy"
  },
  {
    "slug": "rainy_mood",
    "name": "Rainy Mood"
  },
  {
    "slug": "ramen_bowl",
    "name": "Ramen Bowl"
  },
  {
    "slug": "ramen_bowl_toppings",
    "name": "Ramen Bowl (Toppings)"
  },
  {
    "slug": "rawr_xd",
    "name": "Rawr xD"
  },
  {
    "slug": "rec_room_lightning",
    "name": "Rec Room Lightning"
  },
  {
    "slug": "box_red_white",
    "name": "Red Box"
  },
  {
    "slug": "red_lantern",
    "name": "Red Lantern"
  },
  {
    "slug": "red_mana",
    "name": "Red Mana"
  },
  {
    "slug": "teacup_red",
    "name": "Red Teacup"
  },
  {
    "slug": "box_red_white_blue",
    "name": "Red White Box"
  },
  {
    "slug": "reynas_leer",
    "name": "Reyna's Leer"
  },
  {
    "slug": "rift_butterfly",
    "name": "Rift Butterfly"
  },
  {
    "slug": "ring_of_roses_blue",
    "name": "Ring of Roses (Blue)"
  },
  {
    "slug": "ring_of_roses_red",
    "name": "Ring of Roses (Red)"
  },
  {
    "slug": "rocket_puncher",
    "name": "Rocket Puncher"
  },
  {
    "slug": "rose_bearer_blue",
    "name": "Rose Bearer (Blue)"
  },
  {
    "slug": "rose_bearer_pink",
    "name": "Rose Bearer (Pink)"
  },
  {
    "slug": "ruby_hearts",
    "name": "Ruby Hearts"
  },
  {
    "slug": "rumbling",
    "name": "Rumbling"
  },
  {
    "slug": "ryu",
    "name": "Ryu"
  },
  {
    "slug": "sakura",
    "name": "Sakura"
  },
  {
    "slug": "sakura_city",
    "name": "Sakura City"
  },
  {
    "slug": "sakura_ink",
    "name": "Sakura Ink"
  },
  {
    "slug": "sakura_scholar",
    "name": "Sakura Scholar"
  },
  {
    "slug": "sakura_warrior",
    "name": "Sakura Warrior"
  },
  {
    "slug": "sandy_cheeks",
    "name": "Sandy Cheeks"
  },
  {
    "slug": "saw",
    "name": "Saw"
  },
  {
    "slug": "scallywag",
    "name": "Scallywag"
  },
  {
    "slug": "fall_leaves_scarlet",
    "name": "Scarlet Leaves"
  },
  {
    "slug": "scout",
    "name": "Scout"
  },
  {
    "slug": "selyne",
    "name": "Selyne"
  },
  {
    "slug": "shadow",
    "name": "Shadow"
  },
  {
    "slug": "shenron",
    "name": "Shenron"
  },
  {
    "slug": "shield_potion",
    "name": "Shield Potion"
  },
  {
    "slug": "shield_saw",
    "name": "Shield Saw"
  },
  {
    "slug": "shocked",
    "name": "Shocked"
  },
  {
    "slug": "shocked_green",
    "name": "Shocked (Green)"
  },
  {
    "slug": "shocked_yellow",
    "name": "Shocked (Yellow)"
  },
  {
    "slug": "shoto_todoroki",
    "name": "Shoto Todoroki"
  },
  {
    "slug": "shower_stroll",
    "name": "Shower Stroll"
  },
  {
    "slug": "shroomling",
    "name": "Shroomling"
  },
  {
    "slug": "shroomling_blue",
    "name": "Shroomling (Blue)"
  },
  {
    "slug": "shroomling_brown",
    "name": "Shroomling (Brown)"
  },
  {
    "slug": "shroomling_pink",
    "name": "Shroomling (Pink)"
  },
  {
    "slug": "shroomling_purple",
    "name": "Shroomling (Purple)"
  },
  {
    "slug": "shurikens_mask",
    "name": "Shuriken's Mask"
  },
  {
    "slug": "shy",
    "name": "Shy"
  },
  {
    "slug": "shy_in_love",
    "name": "Shy (In Love)"
  },
  {
    "slug": "signal_from_tau_ceti",
    "name": "Signal from Tau Ceti"
  },
  {
    "slug": "silver_surfer",
    "name": "Silver Surfer"
  },
  {
    "slug": "sippy_juice",
    "name": "Sippy Juice"
  },
  {
    "slug": "skate",
    "name": "skate."
  },
  {
    "slug": "skibidi_toilet",
    "name": "Skibidi Toilet"
  },
  {
    "slug": "skull_medallion",
    "name": "Skull Medallion"
  },
  {
    "slug": "skully_charms",
    "name": "Skully Charms"
  },
  {
    "slug": "sleepy_bee",
    "name": "Sleepy Bee"
  },
  {
    "slug": "sleepy_chilledcow",
    "name": "Sleepy ChilledCow"
  },
  {
    "slug": "slither_n_snack",
    "name": "Slither 'n Snack"
  },
  {
    "slug": "slurp_barrel",
    "name": "Slurp Barrel"
  },
  {
    "slug": "green_smoke",
    "name": "Smoke"
  },
  {
    "slug": "snakes_hug",
    "name": "Snake's Hug"
  },
  {
    "slug": "fox_hat_snow",
    "name": "Snow Fox Hat"
  },
  {
    "slug": "snowdrops",
    "name": "Snowdrops"
  },
  {
    "slug": "snowfall",
    "name": "Snowfall"
  },
  {
    "slug": "snowglobe",
    "name": "Snowglobe"
  },
  {
    "slug": "snowglobe_blue",
    "name": "Snowglobe (Blue)"
  },
  {
    "slug": "snowglobe_green",
    "name": "Snowglobe (Green)"
  },
  {
    "slug": "snowglobe_pink",
    "name": "Snowglobe (Pink)"
  },
  {
    "slug": "snowglobe_wood",
    "name": "Snowglobe (Wood)"
  },
  {
    "slug": "icicle_snowing",
    "name": "Snowing Icicle"
  },
  {
    "slug": "owlbear_cub_snowy",
    "name": "Snowy Owlbear Cub"
  },
  {
    "slug": "solar_orbit",
    "name": "Solar Orbit"
  },
  {
    "slug": "soul_leaving_body",
    "name": "Soul Leaving Body"
  },
  {
    "slug": "soul_leaving_body_blue",
    "name": "Soul Leaving Body (Blue)"
  },
  {
    "slug": "space_battle",
    "name": "Space Battle"
  },
  {
    "slug": "speakerwoman",
    "name": "Speakerwoman"
  },
  {
    "slug": "spirit_blossom_karma",
    "name": "Spirit Blossom Karma"
  },
  {
    "slug": "spirit_blossom_morgana",
    "name": "Spirit Blossom Morgana"
  },
  {
    "slug": "spirit_blossom_springs",
    "name": "Spirit Blossom Springs"
  },
  {
    "slug": "spirit_blossom_springs_ahri",
    "name": "Spirit Blossom Springs Ahri"
  },
  {
    "slug": "spirit_blossom_springs_sett",
    "name": "Spirit Blossom Springs Sett"
  },
  {
    "slug": "spirit_blossom_zed",
    "name": "Spirit Blossom Zed"
  },
  {
    "slug": "spirit_embers",
    "name": "Spirit Embers"
  },
  {
    "slug": "split",
    "name": "Split"
  },
  {
    "slug": "spongebob",
    "name": "SpongeBob"
  },
  {
    "slug": "spooky_cat_ears",
    "name": "Spooky Cat Ears"
  },
  {
    "slug": "spooky_cat_ears_midnight",
    "name": "Spooky Cat Ears (Midnight)"
  },
  {
    "slug": "sproutling",
    "name": "Sproutling"
  },
  {
    "slug": "confetti_star",
    "name": "Star Confetti"
  },
  {
    "slug": "stardust",
    "name": "Stardust"
  },
  {
    "slug": "starlight_revolver",
    "name": "Starlight Revolver"
  },
  {
    "slug": "starlight_tiara",
    "name": "Starlight Tiara"
  },
  {
    "slug": "starlight_whales",
    "name": "Starlight Whales"
  },
  {
    "slug": "starry_eyed",
    "name": "Starry Eyed"
  },
  {
    "slug": "starry_eyed_green",
    "name": "Starry Eyed (Green)"
  },
  {
    "slug": "starry_eyed_pink",
    "name": "Starry Eyed (Pink)"
  },
  {
    "slug": "steampunk_cat_ears",
    "name": "Steampunk Cat Ears"
  },
  {
    "slug": "stinkums",
    "name": "Stinkums"
  },
  {
    "slug": "straw_hat",
    "name": "Straw Hat"
  },
  {
    "slug": "strawberry_vine",
    "name": "Strawberry Vine"
  },
  {
    "slug": "street_fighter_6_battle_field",
    "name": "Street Fighter 6 Battle Field"
  },
  {
    "slug": "string_lights",
    "name": "String Lights"
  },
  {
    "slug": "string_lights_aurora",
    "name": "String Lights (Aurora)"
  },
  {
    "slug": "string_lights_dusk",
    "name": "String Lights (Dusk)"
  },
  {
    "slug": "string_lights_ember",
    "name": "String Lights (Ember)"
  },
  {
    "slug": "string_lights_mix",
    "name": "String Lights (Mix)"
  },
  {
    "slug": "study_session",
    "name": "Study Session"
  },
  {
    "slug": "sunflowers",
    "name": "Sunflowers"
  },
  {
    "slug": "supercell",
    "name": "SuperCell"
  },
  {
    "slug": "supply_llama",
    "name": "Supply Llama"
  },
  {
    "slug": "sushi_roll",
    "name": "Sushi Roll"
  },
  {
    "slug": "sweat_drops",
    "name": "Sweat Drops"
  },
  {
    "slug": "sweat_drops_cyan",
    "name": "Sweat Drops (Cyan)"
  },
  {
    "slug": "sweat_drops_pink",
    "name": "Sweat Drops (Pink)"
  },
  {
    "slug": "sweet_tooth",
    "name": "Sweet Tooth"
  },
  {
    "slug": "tactibear_flex",
    "name": "Tactibear Flex"
  },
  {
    "slug": "terrain_tiles",
    "name": "Terrain Tiles"
  },
  {
    "slug": "terrarium",
    "name": "Terrarium"
  },
  {
    "slug": "tga_controller",
    "name": "TGA Controller"
  },
  {
    "slug": "the_anomaly",
    "name": "The Anomaly"
  },
  {
    "slug": "the_atlas_gauntlets",
    "name": "The Atlas Gauntlets"
  },
  {
    "slug": "bad_guys_2",
    "name": "The Bad Guys 2 Trailer"
  },
  {
    "slug": "the_conjuring_last_rites",
    "name": "The Conjuring: Last Rites"
  },
  {
    "slug": "the_entity",
    "name": "The Entity"
  },
  {
    "slug": "the_fantastic_four",
    "name": "The Fantastic Four"
  },
  {
    "slug": "the_final_peel",
    "name": "The Final Peel"
  },
  {
    "slug": "the_hexcore",
    "name": "The Hexcore"
  },
  {
    "slug": "the_mark",
    "name": "The Mark"
  },
  {
    "slug": "the_monster_you_created",
    "name": "The Monster You Created"
  },
  {
    "slug": "the_petal_pack",
    "name": "The Petal Pack"
  },
  {
    "slug": "the_thing",
    "name": "The Thing"
  },
  {
    "slug": "thps_half_pipe",
    "name": "THPS Half Pipe"
  },
  {
    "slug": "timekeepers_clock",
    "name": "Timekeeper's Clock"
  },
  {
    "slug": "toast",
    "name": "Toast"
  },
  {
    "slug": "toilet_lid",
    "name": "Toilet Lid"
  },
  {
    "slug": "tomura_shigaraki",
    "name": "Tomura Shigaraki"
  },
  {
    "slug": "torgal_puppy",
    "name": "Torgal Puppy"
  },
  {
    "slug": "touch_grass",
    "name": "Touch Grass"
  },
  {
    "slug": "towerborne_play",
    "name": "Towerborne Play"
  },
  {
    "slug": "trash",
    "name": "Trash"
  },
  {
    "slug": "travel_ring",
    "name": "Travel Ring"
  },
  {
    "slug": "treasure_and_key",
    "name": "Treasure and Key"
  },
  {
    "slug": "treat_ghost",
    "name": "Treat Ghost"
  },
  {
    "slug": "treat_pumpkin",
    "name": "Treat Pumpkin"
  },
  {
    "slug": "treat_skull",
    "name": "Treat Skull"
  },
  {
    "slug": "treat_spider",
    "name": "Treat Spider"
  },
  {
    "slug": "trick_ghost",
    "name": "Trick Ghost"
  },
  {
    "slug": "trick_pumpkin",
    "name": "Trick Pumpkin"
  },
  {
    "slug": "trick_skull",
    "name": "Trick Skull"
  },
  {
    "slug": "trick_spider",
    "name": "Trick Spider"
  },
  {
    "slug": "tv_woman",
    "name": "TV Woman"
  },
  {
    "slug": "chrysanthemums_twilight",
    "name": "Twilight Chrysanthemums"
  },
  {
    "slug": "ufo",
    "name": "UFO"
  },
  {
    "slug": "sakura_ukon",
    "name": "Ukon Sakura"
  },
  {
    "slug": "ultron",
    "name": "Ultron"
  },
  {
    "slug": "unicorn",
    "name": "Unicorn"
  },
  {
    "slug": "uwu_xp",
    "name": "UwU XP"
  },
  {
    "slug": "valorant_champions_2024",
    "name": "VALORANT Champions 2024"
  },
  {
    "slug": "valorant_summer_kickoff",
    "name": "VALORANT Summer Kickoff"
  },
  {
    "slug": "confetti_vaporwave",
    "name": "Vaporwave Confetti"
  },
  {
    "slug": "dice_violet",
    "name": "Violet Dice"
  },
  {
    "slug": "viper_poison_cloud",
    "name": "Viper Poison Cloud"
  },
  {
    "slug": "wallach_spaceport",
    "name": "Wallach IX Spaceport"
  },
  {
    "slug": "warframe_clem",
    "name": "Warframe Clem"
  },
  {
    "slug": "warp_helmet",
    "name": "Warp Helmet"
  },
  {
    "slug": "water",
    "name": "Water"
  },
  {
    "slug": "wendys_x_wednesday",
    "name": "Wendy’s x Wednesday"
  },
  {
    "slug": "box_white_blue",
    "name": "White Box"
  },
  {
    "slug": "white_mana",
    "name": "White Mana"
  },
  {
    "slug": "wingman_boba",
    "name": "Wingman Boba"
  },
  {
    "slug": "wingmans_got_it",
    "name": "WINGMAN'S GOT IT"
  },
  {
    "slug": "winkle",
    "name": "Winkle"
  },
  {
    "slug": "wizard_hat_blue",
    "name": "Wizard Hat (Blue)"
  },
  {
    "slug": "wizard_hat_purple",
    "name": "Wizard Hat (Purple)"
  },
  {
    "slug": "wizards_staff",
    "name": "Wizard's Staff"
  },
  {
    "slug": "wolf_morph",
    "name": "Wolf Morph"
  },
  {
    "slug": "fall_leaves_woodland",
    "name": "Woodland Leaves"
  },
  {
    "slug": "woolgathering",
    "name": "Woolgathering"
  },
  {
    "slug": "yoda_on_dagobah",
    "name": "Yoda on Dagobah"
  },
  {
    "slug": "yoru_dimensional_drift",
    "name": "Yoru Dimensional Drift"
  },
  {
    "slug": "yunara",
    "name": "Yunara"
  },
  {
    "slug": "zombie_food",
    "name": "Zombie Food"
  },
  {
    "slug": "zombie_food_purple",
    "name": "Zombie Food (Purple)"
  }
]
