-- Add missing columns to profiles table
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS background_gradient TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS custom_font_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS custom_font_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS border_style TEXT DEFAULT 'none';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS panel_height TEXT DEFAULT 'auto';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_position TEXT DEFAULT 'center';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_placement TEXT DEFAULT 'top';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS show_avatar BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS show_name BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS typing_bio BOOLEAN DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS typing_speed INTEGER DEFAULT 50;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS bio_texts TEXT[];
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS enter_enabled BOOLEAN DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS enter_title TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS enter_subtitle TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS enter_show_profile BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS enter_show_title BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS enter_show_subtitle BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS particle_count INTEGER DEFAULT 50;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS cursor_trail_enabled BOOLEAN DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS custom_cursor_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS hover_effect TEXT DEFAULT 'none';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS entrance_animation TEXT DEFAULT 'none';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS tilt_effect BOOLEAN DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS show_view_count BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS show_badges BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS music_show_title BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS music_show_artist BOOLEAN DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS banned_by_username TEXT;
