/**
 * Sync the avatar decoration catalog from the community-maintained
 * Discord avatar decoration mirror (github.com/Kadantte/discord-fake-
 * avatar-decorations). Assets are served via the jsdelivr CDN.
 *
 * Run with: `tsx scripts/sync-decor-catalog.ts`
 *
 * Writes `lib/avatar-decorations.generated.ts` with all decorations
 * (slug + name), sorted alphabetically by name.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'

const SOURCE_URL =
  'https://raw.githubusercontent.com/Kadantte/discord-fake-avatar-decorations/main/src/data/decorations.js'
const OUT_FILE = path.join(process.cwd(), 'lib', 'avatar-decorations.generated.ts')

async function main() {
  console.log('Fetching', SOURCE_URL)
  const res = await fetch(SOURCE_URL)
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const txt = await res.text()

  // Decoration objects look like: { n: "Name", d: "Description", f: "slug" }
  // Section/badge objects look like: { n: "Section", b: "section_slug", ...}
  // We only want the `f:` keyed ones.
  const re =
    /\{\s*n:\s*"((?:\\.|[^"\\])+)"\s*,\s*(?:d:\s*"(?:\\.|[^"\\])*"\s*,\s*)?f:\s*"([^"]+)"\s*,?\s*\}/g

  const items: Array<{ slug: string; name: string }> = []
  let m: RegExpExecArray | null
  while ((m = re.exec(txt)) !== null) {
    items.push({ name: m[1], slug: m[2] })
  }
  const seen = new Set<string>()
  const unique = items.filter((x) => {
    if (seen.has(x.slug)) return false
    seen.add(x.slug)
    return true
  })
  unique.sort((a, b) => a.name.localeCompare(b.name))

  const header = `// Generated by scripts/sync-decor-catalog.ts from
// ${SOURCE_URL}
// (a community mirror of Discord's official avatar decoration store, slug-keyed).
// DO NOT EDIT BY HAND.
import type { AvatarDecoration } from './avatar-decorations'
export const GENERATED_DECORATIONS: AvatarDecoration[] = `

  fs.writeFileSync(OUT_FILE, header + JSON.stringify(unique, null, 2) + '\n')
  console.log(`Wrote ${OUT_FILE} (${unique.length} decorations)`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
