/**
 * Load a profile preset into the live profile.
 *
 * POST { slot: 1 | 2 | 3 } →
 *   1. fetch the preset for (user_id, slot)
 *   2. UPDATE profiles with the snapshot's `config.profile` fields
 *      (only PROFILE_ALLOWED_COLUMNS - identity/security fields are
 *      never touched even if a malicious snapshot has them)
 *   3. DELETE + INSERT for each child table (social_links,
 *      custom_buttons, profile_badge_loadout, profile_title_loadout,
 *      music_history, widgets) - child rows always belong to the
 *      loading user via the user_id override
 *
 * Not transactional across all five tables (Supabase JS doesn't
 * expose multi-statement transactions), so a network blip between
 * steps could leave the profile partially updated. We mitigate by
 * doing the destructive DELETE pass first per child table and
 * recovering by re-running the load. The profile UPDATE happens
 * last so a half-success leaves the visual look from before the
 * load - easier to recover than half-new data with old chrome.
 */

import { NextResponse } from 'next/server'
import { getApiUser } from '@/lib/api-auth'
import { createAdminClient } from '@/lib/supabase/admin'
import { withRateLimit } from '@/lib/rate-limit'
import { PROFILE_ALLOWED_COLUMNS } from '@/lib/profile-columns'
import { stripPremiumFields } from '@/lib/strip-premium-fields'
import { getFreeEventActive } from '@/lib/get-free-event-active'

type SlotNumber = 1 | 2 | 3 | 4 | 5

function parseSlot(raw: unknown): SlotNumber | null {
  const n = Number(raw)
  if (n >= 1 && n <= 5 && Number.isInteger(n)) return n as SlotNumber
  return null
}

// Stripping identity / DB-managed fields from snapshotted rows
// before re-inserting. `id` and `created_at` get regenerated by
// the DB defaults. `user_id` is force-set to the loading user
// (a snapshot from user A can never re-land as user B because
// the API auth already verified ownership, but force-setting
// is defence in depth).
function sanitizeChildRow(row: Record<string, unknown>, userId: string): Record<string, unknown> {
  const { id: _id, created_at: _created, ...rest } = row
  return { ...rest, user_id: userId }
}

export async function POST(request: Request) {
  try {
    const rateLimit = await withRateLimit(request, 'profileUpdate')
    if (rateLimit.response) return rateLimit.response

    const profile = await getApiUser()
    if (!profile) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const body = await request.json().catch(() => ({}))
    const slot = parseSlot(body.slot)
    if (!slot) {
      return NextResponse.json({ error: 'slot must be 1-5' }, { status: 400 })
    }

    const admin = createAdminClient()

    const { data: preset, error: fetchErr } = await admin
      .from('profile_presets')
      .select('config')
      .eq('user_id', profile.id)
      .eq('slot', slot)
      .single()

    if (fetchErr || !preset) {
      return NextResponse.json({ error: 'Preset not found' }, { status: 404 })
    }

    const config = preset.config as {
      profile?: Record<string, unknown>
      social_links?: Record<string, unknown>[]
      custom_buttons?: Record<string, unknown>[]
      badge_loadout?: Record<string, unknown>[]
      title_loadout?: Record<string, unknown>[]
      music_history?: Record<string, unknown>[]
      widgets?: Record<string, unknown>[]
    }

    // Filter the profile columns to the allowlist again, defensively.
    // Even if a snapshot's `profile` blob has extra keys (e.g. from
    // a future schema where it was once snapshotted then renamed),
    // we only write back columns that are still in the allowlist.
    const profileUpdates: Record<string, unknown> = {}
    if (config.profile) {
      for (const col of PROFILE_ALLOWED_COLUMNS) {
        if (col in config.profile) profileUpdates[col] = config.profile[col]
      }
    }

    // Premium gate the loaded snapshot. A user can save a preset while
    // they're premium and re-load it months later after their premium
    // lapses - without this strip, premium-only fields (custom fonts,
    // outline glow, gradient, monochrome icons, display_name overlay,
    // embed metadata, etc) would silently come back to life. Mirrors the
    // gate /api/profile, /api/appearance, /api/effects already apply.
    const freeEvent = await getFreeEventActive()
    const isPremium = (profile as any).premium_active === true || freeEvent
    const stripped = stripPremiumFields(profileUpdates, isPremium)
    Object.assign(profileUpdates, stripped.updates)
    if (stripped.strippedKeys.length > 0) {
      console.log('[presets/load] stripped premium fields for non-premium user:', stripped.strippedKeys.join(', '))
    }

    // Wipe child tables first so the load is idempotent - re-loading
    // the same slot doesn't pile up duplicate rows.
    await Promise.all([
      admin.from('social_links').delete().eq('user_id', profile.id),
      admin.from('custom_buttons').delete().eq('user_id', profile.id),
      admin.from('profile_badge_loadout').delete().eq('user_id', profile.id),
      admin.from('profile_title_loadout').delete().eq('user_id', profile.id),
      admin.from('music_history').delete().eq('user_id', profile.id),
      admin.from('widgets').delete().eq('user_id', profile.id),
    ])

    // Re-insert child rows from the snapshot. Each table is optional
    // - if the snapshot doesn't include a list (older preset format)
    // we leave the table empty.
    if (config.social_links?.length) {
      const rows = config.social_links.map((r) => sanitizeChildRow(r, profile.id))
      const { error } = await admin.from('social_links').insert(rows)
      if (error) console.error('[presets/load] social_links insert error:', error)
    }
    if (config.custom_buttons?.length) {
      const rows = config.custom_buttons.map((r) => sanitizeChildRow(r, profile.id))
      const { error } = await admin.from('custom_buttons').insert(rows)
      if (error) console.error('[presets/load] custom_buttons insert error:', error)
    }
    if (config.badge_loadout?.length) {
      // Only re-equip badges the user still OWNS. A preset saved while holding
      // a rank badge must not re-grant it after it was revoked (e.g. dropping
      // out of the leaderboard top 3). profile_badges is the ownership truth.
      const { data: owned } = await admin
        .from('profile_badges')
        .select('badge_id')
        .eq('user_id', profile.id)
      const ownedIds = new Set((owned || []).map((r: any) => r.badge_id))
      const rows = config.badge_loadout
        .filter((r: any) => r?.badge_id && ownedIds.has(r.badge_id))
        .map((r) => sanitizeChildRow(r, profile.id))
      if (rows.length) {
        const { error } = await admin.from('profile_badge_loadout').insert(rows)
        if (error) console.error('[presets/load] badge_loadout insert error:', error)
      }
    }
    if (config.title_loadout?.length) {
      const rows = config.title_loadout.map((r) => sanitizeChildRow(r, profile.id))
      const { error } = await admin.from('profile_title_loadout').insert(rows)
      if (error) console.error('[presets/load] title_loadout insert error:', error)
    }
    if (config.music_history?.length) {
      const rows = config.music_history.map((r) => sanitizeChildRow(r, profile.id))
      const { error } = await admin.from('music_history').insert(rows)
      if (error) console.error('[presets/load] music_history insert error:', error)
    }
    if (config.widgets?.length) {
      const rows = config.widgets.map((r) => sanitizeChildRow(r, profile.id))
      const { error } = await admin.from('widgets').insert(rows)
      if (error) console.error('[presets/load] widgets insert error:', error)
    }

    // Update the profile row last so a partial failure leaves the
    // previous visual look intact while the child rows are being
    // restored on retry.
    if (Object.keys(profileUpdates).length > 0) {
      const { error } = await admin
        .from('profiles')
        .update(profileUpdates)
        .eq('id', profile.id)
      if (error) {
        console.error('[presets/load] profile update error:', error)
        return NextResponse.json({ error: 'Failed to apply preset' }, { status: 500 })
      }
    }

    // Stamp last_loaded_at on the loaded slot so the UI can badge
    // it as the currently-active preset. Best-effort - a failed
    // update here doesn't break the load.
    await admin
      .from('profile_presets')
      .update({ last_loaded_at: new Date().toISOString() })
      .eq('user_id', profile.id)
      .eq('slot', slot)
      .then(({ error }) => {
        if (error) console.warn('[presets/load] last_loaded_at update failed:', error.message)
      })

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error('[presets/load] error:', error)
    return NextResponse.json({ error: 'Failed to load preset' }, { status: 500 })
  }
}
